version: '3.3'

services:
        servicediscovery:
                build: ./servicediscovery
                container_name: servicediscovery
                ports: 
                        - "8761:8761"
                networks:
                        - private_network
        api-gateway:
                build: 
                        context: ./api-gateway
                        dockerfile: Dockerfile.api-gateway
                container_name: api-gateway
                ports:
                        - "8080:8080"
                depends_on:
                        - servicediscovery
                        - db-gateway
                networks: 
                        - private_network
                links:
                        - db-gateway:database
        ambienteservice:
                build:
                        context: ./ambienteservice
                        dockerfile: Dockerfile.ambienteservice
                container_name: ambienteservice
                depends_on:
                        - api-gateway
                        - db-ambienteservice
                networks:
                        - private_network
                links:
                        - db-ambienteservice:database
        cursoservice:
                build:
                        context: ./cursoservice
                        dockerfile: Dockerfile.cursoservice
                container_name: cursoservice
                depends_on:
                        - api-gateway
                        - db-cursoservice
                networks:
                        - private_network
                links:
                        - db-cursoservice:database
        coordenadorservice:
                build:
                        context: ./coordenadorservice
                        dockerfile: Dockerfile.coordenadorservice
                container_name: coordenadorservice
                depends_on:
                        - api-gateway
                        - db-coordenadorservice
                networks:
                        - private_network
                links:
                        - db-coordenadorservice:database
        db-gateway:
                build:
                        context: ./api-gateway
                        dockerfile: Dockerfile.db
                container_name: db-gateway
        db-ambienteservice:
                build:
                        context: ./ambienteservice
                        dockerfile: Dockerfile.db
                container_name: db-ambienteservice
        db-cursoservice:
                build:
                        context: ./cursoservice
                        dockerfile: Dockerfile.db
                container_name: db-cursoservice
        db-coordenadorservice:
                build:
                        context: ./coordenadorservice
                        dockerfile: Dockerfile.db
                container_name: db-coordenadorservice
networks:
        private_network:
                driver: bridge
